name: Hassan Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Light mode
      - name: Generate GitHub Metrics (Light)
        uses: lowlighter/metrics@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: HassanFirouzi
          filename: metrics-light.svg
          base: header,activity
          languages: yes
          community: yes
          repositories: yes

      # Dark mode
      - name: Generate GitHub Metrics (Dark)
        uses: lowlighter/metrics@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: HassanFirouzi
          filename: metrics-dark.svg
          base: header,activity
          languages: yes
          community: yes
          repositories: yes
          config_theme: dark

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metrics-light.svg metrics-dark.svg
          git commit -m "update metrics" || echo "no changes"
          git push origin HEAD





        

